version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo_lagunpay
    restart: always
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./db/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./db/data:/db/data
    env_file:
      - .env
    
  node:
    build: .
    container_name: node_lagunpay
    restart: always
    ports:
      - ${APP_PORT}:3000
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules